# Generated by Django 4.0.1 on 2022-01-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermaster',
            name='last_name',
        ),
    ]
